packages:
  - examples/*
catalog:
  "@biomejs/biome": 1.9.4
  "@tailwindcss/typography": 0.5.15
  "@tanstack/react-query": 5.59.16
  "@tidbcloud/serverless": 0.2.0
  "@trpc/client": 11.0.0-rc.660
  "@trpc/next": 11.0.0-rc.660
  "@trpc/react-query": 11.0.0-rc.660
  "@trpc/server": 11.0.0-rc.660
  "@types/node": ^20
  "@types/react": ^19
  "@types/react-dom": ^19
  ai: 4.0.18
  clsx: 2.1.1
  daisyui: 4.12.14
  next: 15.1.0
  ollama-ai-provider: 0.16.0
  postcss: 8.4.49
  prism-react-renderer: 2.4.0
  react: 19.0.0
  react-dom: 19.0.0
  react-markdown: 9.0.1
  react-use: 17.5.1
  tailwindcss: 3.4.1
  typescript: 5.7.2
  zod: 3.23.8
